services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - $PWD/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/src:/var/www
      - $PWD/data:/mnt/site_data/realpath
    ports:
      - 80:80
  php:
    image: php:8.1-fpm-alpine
    volumes:
      - $PWD/src:/var/www