services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - $PWD/conf.d:/etc/nginx/conf.d
      - $PWD/src:/var/www
      - $PWD/data:/mnt/site_data/realpath
    ports:
      - 80:80
  php:
    image: php:8.1-fpm-alpine
    volumes:
      - $PWD/src:/var/www